bboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]
if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

main/urls.py
from email.errors import NoBoundaryInMultipartDefect
from django.urls import path
from .views import BBLogoutView, BbLoginView, index, other_page, profile
from .views import ChangeUserInfoView, BBPaswordChangeView, RegisterUserView, RegisterDoneViews
app_name = 'main'
urlpatterns = [
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index'),
    path('accounts/login/', BbLoginView.as_view(), name='login'),
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/logout/', BBLogoutView.as_view(), name='logout'),
    path('accounts/password_change/', BBPaswordChangeView.as_view(), name='password_change'),
    path('accounts/register/done/', RegisterDoneViews.as_view(), name='register_done'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
]

main/models.py
from pyexpat import model
from tabnanny import verbose
from django.db import models
from django.contrib.auth.models import AbstractUser

class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name='Прошел активацию?')
    send_messages = models.BooleanField(default=True, verbose_name='Слать оповещения о новых комментариях?')


    class Meta(AbstractUser.Meta):
        pass

main/forms.py
from io import UnsupportedOperation
from attr import fields
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError

from .apps import user_registered
from .models import AdvUser

# change user info
class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'first_name', 'last_name',
        'send_messages')

# register new user
class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль', 
        widget=forms.PasswordInput,
        help_text=password_validation.password_validators_help_text_html())
    password2 =forms.CharField(label='Пароль (повторно)',
        widget=forms.PasswordInput,
        help_text='Введите тот же самый пароль еще раз для проверки')

    # validation password
    def clean_password(self):
        password1 = self.cleaned_data['password1']
        if password1:
            password_validation.validate_password(password1)

    # equal passwords
    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
                'Введенные пароли не совпадают', code='password_mismatch')}
            raise ValidationError(errors)
    
    # save and send signal
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_active = False
        user.is_activated = False
        if commit:
            user.save()
        user_registered.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = ('username', 'email', 'password1', 'password2',
        'first_name', 'last_name', 'send_messages')

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView, CreateView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.views.generic.base import TemplateView

from .models import AdvUser
from .forms import ChangeUserInfoForm, RegisterUserForm

# user profile, authorizied only
@login_required
def profile(request):
    return render(request, 'main/profile.html')

# rendering main page
def index(request):
    return render(request, 'main/index.html')

# rendering page by name or exception
def other_page(request, page):
    try:
        template = get_template('main/' + page + '.html')
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


# login
class BbLoginView(LoginView):
    template_name = 'main/login.html'

# logout
class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'main/logout.html'

# change user info
class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = AdvUser
    template_name = 'main/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('main:profile')
    success_message = 'Данные пользователя изменены'

    # take an id of current user
    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    # take a queryset by id
    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

# password change
class BBPaswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = 'main/password_change.html'
    success_url = reverse_lazy('main:profile')
    success_message = 'Пароль пользователя изменен'

# register user
class RegisterUserView(CreateView):
    model = AdvUser
    template_name = 'main/rregister_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('main:register_done')

# success register message
class RegisterDoneViews(TemplateView):
    template_name = 'main/register_done.html'

main/templates/layout/basic.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="'viewport"
        content="'width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}Главная{% endblock %} - Доска
        обьявлений</title>
        {% bootstrap_css %}
        <link rel = "stylesheet" type="text/css"
        href="{% static 'main/style.css' %}">
        {% bootstrap_javascript jquery='slim' %}
    </head>
    <body class="'container-fluid">
        <header class="'mb-4">
            <h1 class="display-1 text-center">Обьявления</h1>
        </header>
        <div class="row">
            <ul class="col nav justify-content-end border">
                <li class="nav-item"><a class="nav-link"
                href="{% url 'main:register' %}">Регистрация</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown-toggle">
                    <a class="nav-link dropdown-toggle"
                    data-toggle="dropdown"
                    href="#" role="button" aria-haspopup="true"
                    aria-expanded="false">Профиль</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'main:profile' %}">Мои 
                            обьявления</a>
                        <a class="dropdown-item" href="{% url 'main:profile_change' %}">Изменить 
                            личные данные</a>
                        <a class="dropdown-item" href="{% url 'main:password_change' %}">Изменить 
                            пароль</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'main:logout' %}">Выйти</a> 
                        <div class="dropdown-divider"></div> 
                        <a class="dropdown-item" href="#">Удалить</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item"><a class="nav-link" 
                href="{% url 'main:login' %}">Вход</a></li>
                {% endif %}
            </ul>
        </div>
        <div class="row">
            <nav class="col-md-auto nav flex-column border">
                <a class="nav-link root"
                href="{% url 'main:index'%}">Главная</a>
                <span class="nav-link root font-weight-bold">
                Недвижимость</span>
                <a class="nav-link" href="#">Жилье</a>
                <a class="nav-link" href="#">Склады</a>
                <a class="nav-link" href="#">Гаражи</a>
                <span class="nav-link root font-weight-bold">
                Транспорт</span>
                <a class="nav-link" href="#">Легковой</a>
                <a class="nav-link" href="#">Грузовой</a>
                <a class="nav-link root" href="{% url 'main:other' page='about' %}">
                О сайте</a>
            </nav>
            <section class="col bordder py-2">
                {% bootstrap_messages %}
                {% block content %}
                {% endblock %}
            </section>
        </div>
        <footer class="mt-3">
            <p class="text-right font-italic">&copy; читатели.</p>
        </footer>
    </body>
</html>

main/templates/main/about.html
{% extends "layout/basic.html" %}
{% block title %}О сайте{% endblock %}
{% block content %}
<h2>О сайте</h2>
<p>Сайт для публикации обьявлений о продаже, разбитых на рубрики.</p>
<p>Все права принадлежат читателям книги &laquo;Django 3.0&raquo;.</p>
{% endblock %}

main/templates/main/change_user_info.html
{% extends "layout/basic.html "%}
{% load bootstrap4 %}
{% block title %}Правка личнх данных{% endblock %}
{% block content%}
<h2>Правка личных данных пльзоваеля {{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    {% buttons submit='Сохранить' %}{% endbuttons %}
</form>
{% endblock%}

main/templates/main/index.html
{% extends "layout/basic.html" %}
{% block content %}
<h2>Последние 10 обьявлений</h2>
{% endblock %}

main/templates/main/login.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% block title %}Вход{% endblock %}
{% block content %}
<h2>Вход</h2>
{% if user.is_authenticated %}
<p>Вы уже выполнили вход</p>
{% else %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <input type="hidden" name="next" value="{{ next }}">
    {% buttons submit='Войти' %}{% endbuttons %}
</form>
{% endif %}
{% endblock %}

main/templates/main/logout.html
{% extends "layout/basic.html" %}
{% block title %}Выход{% endblock %}
{% block content %}
<h2>Выход</h2>
<p>Вы успешно вышли с сайта.</p>
{% endblock %}

main/templates/main/password_change.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% block title %}Смена пароля{% endblock %}
{% block content %}
<h2>Смена пароля пользовател {{ user.username }}</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horzontal' %}
    {% buttons submit='Сменить пароль' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/profile.html
{% extends "layout/basic.html" %}
{% block title %}Профиль пользователя{% endblock %}
{% block content %}
<h2>Профиль пользователя  {{ user.username }}</h2>
{% if user.first_name and user.last_name %}
<p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}!</p>
{% else %}
<p>Здравствуйте!</p>
{% endif %}
<h3>Ваши обьявления</h3>
{% endblock %}

main/templates/main/register_done.html
{% extends "layout/basic.html" %}
{% block title %}Регистрация завершена.{% endblock %}
{% block content %}
<h2>Регистрация</h2>
<p>Регистрация пользователя завершена.</p>
<p>На адрес электронной почты, указанной пользователем,
выслано письмо для активации</p>
{% endblock %}

main/templates/main/register_user.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% block title %}Регистрация{% endblock %}
{% block content %}
<h2>Регистрация нового пользователя</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horzontal' %}
    {% buttons submit='Зарегистрироваться' %}{% endbuttons %}
</form>
{% endblock %}